services:
  ragflow-backend:
    image: ragflow_light:v1.1
    container_name: ragflow-backend
    ports:
      - "9380:9380"  # gunicorn 配置的端口
    volumes:
      - ./logs:/ragflow/logs  # 日志持久化
      - ./conf:/ragflow/conf  # 配置文件持久化
    environment:
      - WS=1  # 任务执行器数量，可以根据需要调整
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9380/health"]
      interval: 30s
      timeout: 10s
      retries: 3 

  openkag-chatbot:
    image: openkag:chatbot
    container_name: openkag-chatbot
    restart: unless-stopped
    ports:
      - "18000:8000"
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    volumes:
      - ./chatbot/logs:/app/logs
      - ./chatbot/config:/app/config:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  whisper-live:
    image: whisper-live:openkag
    container_name: whisper-openkag
    ports:
      - "9090:9090"
    environment:
      - PORT=9090